### PR TITLE
fix bug:in the prof result internal method does not display class name

### PR DESCRIPTION
**Pull request by zhaoxiwu**
in the prof result does not display class name(internal method in extensions). like this:
extension Test::dotest().
in prof result just display "dotest" not  "Test:dotest".
and this pr fix this bug.

### CODE REVIEW

**Comment by rustjson** [comment]
But I remeber that I had use this to profiled `yaf` and I believe it shows the right things. But it's long time ago and I am not pretty sure right now, Can you provider some tests anyway, that would be great! thanks!

**Comment by zhaoxiwu** [comment]
yes, when I use xhprof to profiled my php code, and found this bug. the fellow is some result I got.
ps: ap just like yaf（actually， ap is the oldest version of yaf）

before fix:
image

after fix:
image

**Comment by glowdan** [comment]
The question occurs on our system. The redis::get, Yac::get and others are replaced to 'get'.

Thank you for solve the problem.

**Comment by chiangzg** [comment]
23333

**Comment by rustjson** [comment]
同学们，在github上请讲English

**Pull request merged**
